fav_movies = ["sandlot", "Lego Movie", "chicken"]
print(len(fav_movies))
fav_movies.append("Iron man")
print(len(fav_movies))
print(fav_movies)
fav_movies.insert(1,"Batman")
print(fav_movies)
del(fav_movies[0])
print(fav_movies)
del(fav_movies[0])
print(fav_movies)
del(fav_movies[0])
print(fav_movies)
del(fav_movies[0])
print(fav_movies)